name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: docker compose up
      run: docker compose up --build --force-recreate -d
