name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: cd
      run: cd && cd dizel && git pull
    - name: docker
      run: docker compose up --build --force-recreate -d
